### ISSUE TITLE
Dependency on deprecated Octokit

### ISSUE THREAD

**Issue by jbrezmorf** [avakar/tag-and-release#5]
Code:
```
- name: Release
  uses: avakar/tag-and-release@v1
  with:
      tag_name: v${{ steps.getversion.outputs.version }}
      release_name: release_${{ steps.getversion.outputs.version }}
  env:
      GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
```
results in the error:
```
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
```
